### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ShinySaana** [Calmynt/BendeRS#3]
What license would BendeRS use? Should we discuss it or do we have something already decided?

**Comment by Calmynt** [comment]
I'm not sure whether we should use GPL or MIT to be honest.

**Comment by LunarLambda** [comment]
I'm a big fan of MPL which is a sort of middle ground between LGPL and MIT.

**Comment by Calmynt** [comment]
After checking the differences between MIT and MPL, I think I'd prefer MPL as well.
